// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmWsFkBHl3ss2047awnZZkJmCXzDilpU4',
    appId: '1:1019225935180:web:7b2001aa5479ba15d1d3e9',
    messagingSenderId: '1019225935180',
    projectId: 'babylon-international-demo',
    authDomain: 'babylon-international-demo.firebaseapp.com',
    storageBucket: 'babylon-international-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gRC0vM6FtrsRQApYxwwmRzsYD9TMS58',
    appId: '1:1019225935180:android:cd97349ad48cae15d1d3e9',
    messagingSenderId: '1019225935180',
    projectId: 'babylon-international-demo',
    storageBucket: 'babylon-international-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7mVzeEQ-6A4KNhgdbMT_R-OXFwIFZiGQ',
    appId: '1:1019225935180:ios:64a538ebb8b72897d1d3e9',
    messagingSenderId: '1019225935180',
    projectId: 'babylon-international-demo',
    storageBucket: 'babylon-international-demo.firebasestorage.app',
    iosBundleId: 'com.example.babylonInternshipDemo',
  );
}
